nginx:
  image: nginx:1.15
  volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/site.template:ro
      - ./nginx/server.key:/etc/nginx/ssl/nginx.key:ro
      - ./nginx/server.crt:/etc/nginx/ssl/nginx.crt:ro
      - /usr/share/nginx/modules/:/usr/share/nginx/modules/:ro
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /usr/share/nginx/html:/usr/share/nginx/html:ro
      - /etc/nginx/default.d/:/etc/nginx/default.d/:ro
      - .:/data/www
  ports:
    # or 8080:8080
      - "443:443"
  links:
      - "girder:girder"
  # environment:
  #     - NGINX_HOST=datavault.dev.ncsa.illinois.edu
  #     - NGINX_PORT=80
  # command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  command: [nginx, '-g', 'daemon off;']



mongodb:
  image: mongo:3.2
  ports:
    - "27017"
  volumes:
    - "/data/db"


    
girder:
  build: .
  dockerfile: Dockerfile
  ports:
    - "9000:8080"
  links:
    - "mongodb:mongodb"
  command: --host 0.0.0.0 --database mongodb://mongodb:27017/girder
