nginx:
  image: nginx:1.12.2
  volumes:
      - ./etc/nginx/default.d/girder.conf:/etc/nginx/conf.d/site.template
      - ./etc/pki/nginx/private/server.key:/etc/nginx/ssl/nginx.key
      - ./etc/pki/nginx/server.crt:/etc/nginx/ssl/nginx.crt
      - .:/data/www
  ports:
    # or 8080:8080
      - "443:443"
  links:
      - "girder:girder"
  environment:
      - NGINX_HOST=datavault.dev.ncsa.illinois.edu
      - NGINX_PORT=80
  command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"




mongodb:
  image: mongo:3.2
  ports:
    - "27017"
  volumes:
    - "/data/db"


    
girder:
  build: .
  dockerfile: Dockerfile
  ports:
    - "9000:8080"
  links:
    - "mongodb:mongodb"
  command: --host 0.0.0.0 --database mongodb://mongodb:27017/girder
