# nginx:
#   image: nginx:1.15
#   volumes:
#       # - ./nginx/girder.conf:/etc/nginx/default.d/girder.conf
#       # - ./nginx/server.key:/etc/nginx/ssl/nginx.key
#       - ./nginx/etc/nginx:/etc/nginx/
#       - ./nginx/share/nginx:/usr/share/nginx
#       - .:/data/www
#   ports:
#     # or 8080:8080
#       - "443:443"
#   links:
#       - "girder:girder"
#   command: [nginx, '-g', 'daemon off;']



mongodb:
  image: mongo:3.2
  ports:
    - "27017"
  volumes:
    - "/data/db"


    
girder:
  build: .
  dockerfile: Dockerfile
  ports:
    - "9000:8080"
  links:
    - "mongodb:mongodb"
  volumes:
    - ../girder:/girder
  command: --host 0.0.0.0 --database mongodb://mongodb:27017/girder
